### PR TITLE
Support basename options

### PR DESCRIPTION
**Pull request by FranckErnewein**
If your application run in a subdirectory ( `http://website.com/my-app/` )
you can pass `/my-app/` to `Application` constructor.

`history`will be build with `useBasename` 

If you want to test, go in `/sample/` directory, then run:

```
NODE_ENV=production webpack --config webpack.config.js --progress --colors && http-server
```

(assuming you installed `http-server` globally)

### CODE REVIEW

**Comment by yrashk** [comment]
Thanks! :heart:

**Comment by FranckErnewein** [comment]
I forgot to commit  `sample/webpack.config.js` that I used to build the sample

``` js
var conf = require('../default-webpack-config');

conf.output.publicPath =  '/build/';
conf.output.path =  './build/';

module.exports = conf;
```

It's just need if you want to test.
If you want I can create a new PR (but it's not mandatory)

**Comment by yrashk** [comment]
Can you send it with one more PR? Thanks!

**Comment by FranckErnewein** [comment]
done: https://github.com/reactuate/reactuate/pull/34 

npm release planned soon ? :)

**Comment by yrashk** [comment]
Published 0.1.21! 🙇

**Comment by FranckErnewein** [comment]
👍

**Pull request merged**
